-- CONTRATO_DEMO.md: corrige un bug real encontrado en la primera prueba en navegador de
-- revertir_demo() (20261029). 25 de las 44 tablas tenant-scoped tienen su columna id como
-- GENERATED ALWAYS AS IDENTITY (no GENERATED BY DEFAULT ni default gen_random_uuid()) --
-- Postgres rechaza un INSERT ... SELECT plano que traiga valores explícitos para esa columna
-- ("cannot insert a non-DEFAULT value into column \"id\"") salvo que se use
-- OVERRIDING SYSTEM VALUE. El resto de la función no cambia; solo el INSERT del segundo bucle.
-- OVERRIDING SYSTEM VALUE es un no-op inofensivo en las tablas sin columnas identity, así que se
-- añade de forma incondicional a las 44 en vez de distinguir cuáles lo necesitan.
create or replace function revertir_demo(p_sesion_id uuid, p_motivo text)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_negocio_id uuid;
  v_reverted_at timestamptz;
  v_started_at timestamptz;
  v_hay_sesion_mas_nueva boolean;
  v_tabla text;
begin
  select negocio_id, reverted_at, started_at
  into v_negocio_id, v_reverted_at, v_started_at
  from demo_sesiones
  where id = p_sesion_id;

  if v_negocio_id is null then
    raise exception 'revertir_demo: sesion % no existe', p_sesion_id;
  end if;

  perform pg_advisory_xact_lock(hashtext('demo:' || v_negocio_id::text));

  if auth.uid() is not null then
    if negocio_actual() <> v_negocio_id then
      raise exception 'revertir_demo: el usuario autenticado no pertenece al tenant demo';
    end if;
  end if;

  if v_reverted_at is not null then
    return;
  end if;

  select exists(
    select 1 from demo_sesiones
    where negocio_id = v_negocio_id and started_at > v_started_at
  ) into v_hay_sesion_mas_nueva;

  if v_hay_sesion_mas_nueva then
    update demo_sesiones set reverted_at = now(), revert_reason = 'superseded' where id = p_sesion_id;
    return;
  end if;

  set constraints all deferred;

  foreach v_tabla in array demo_tablas_tenant() loop
    execute format('delete from %I where negocio_id = %L', v_tabla, v_negocio_id);
  end loop;

  foreach v_tabla in array demo_tablas_tenant() loop
    execute format('insert into %I overriding system value select * from demo_snapshot.%I', v_tabla, v_tabla);
  end loop;

  update demo_sesiones set reverted_at = now(), revert_reason = p_motivo where id = p_sesion_id;
end;
$$;
