-- categorias_articulo: convierte articulos_compra.categoria de texto libre
-- sin validación a un conjunto controlado (tabla + FK), y añade
-- categorias_articulo.acronimo como base del nuevo formato de código de
-- artículo (acronimo_categoria-contador_proveedor-contador_calidad),
-- generado ahora en el frontend al dar de alta un artículo — ver
-- Articulos.jsx. No cambia la relación con codigo_lote/generar_codigo():
-- el trigger existente sigue leyendo articulos_compra.codigo tal cual esté,
-- solo que ahora recibe un valor estructurado en vez de una sigla
-- arbitraria (efecto colateral positivo: cada combinación
-- proveedor+calidad tendrá su propia clave en secuencias_lote, ya no
-- comparten el cajón 'XXX' los artículos sin código).
--
-- Migra los 4 valores reales de categoria — con una corrección: "Mezcla"
-- (categoría real de Huevina) era un error de tecleo heredado (nombre del
-- semielaborado, no una categoría de producto), se migra a "Lácteos y
-- Ovoproductos", confirmado con el usuario antes de aplicar.
--
-- ingredientes.categoria_id (NOT NULL): cada ingrediente pertenece a una
-- categoría — el ingrediente "Huevina" ya existente se migra a la misma
-- categoría corregida. El selector "vincular artículo" en Ingredientes.jsx
-- filtra ahora por esa categoría, además de excluir ya vinculados.
--
-- Probado en transacción de prueba (con ROLLBACK) antes de aplicar: las 4
-- categorías, la migración de los 5 artículos reales y del ingrediente
-- Huevina, el NOT NULL en ambas tablas, la generación de código simulada
-- (LYO-02-01 para un artículo nuevo vinculado a un ingrediente que ya
-- tenía 1 artículo; LYO-01-01 para un ingrediente nuevo) y el filtro por
-- categoría en el selector de vinculación — todo verificado antes de
-- aplicar en firme. Verificado también en runtime real (login real,
-- Articulos.jsx cargando con las 4 categorías y el selector de ingrediente
-- reaccionando a la categoría elegida, 0 errores de consola).

create table categorias_articulo (
  id bigint generated by default as identity primary key,
  nombre text not null,
  acronimo text not null,
  negocio_id uuid not null default 'a8acb3aa-e8f2-4a04-83f4-e6b0ca4e2d00' references negocios(id),
  created_at timestamptz not null default now()
);

alter table categorias_articulo enable row level security;
create policy "Acceso total temporal" on categorias_articulo for all
  using (auth.role() = 'authenticated' and negocio_id = 'a8acb3aa-e8f2-4a04-83f4-e6b0ca4e2d00'::uuid)
  with check (auth.role() = 'authenticated' and negocio_id = 'a8acb3aa-e8f2-4a04-83f4-e6b0ca4e2d00'::uuid);
grant select, insert, update, delete on categorias_articulo to authenticated;

insert into categorias_articulo (nombre, acronimo) values
  ('Verduras', 'VEG'),
  ('Lácteos y Ovoproductos', 'LYO'),
  ('Cocina', 'COC'),
  ('Packaging', 'PKG');

alter table articulos_compra add column categoria_id bigint references categorias_articulo(id);

update articulos_compra set categoria_id = (select id from categorias_articulo where nombre = 'Verduras') where categoria = 'Verduras';
update articulos_compra set categoria_id = (select id from categorias_articulo where nombre = 'Lácteos y Ovoproductos') where categoria = 'Mezcla';
update articulos_compra set categoria_id = (select id from categorias_articulo where nombre = 'Cocina') where categoria = 'Cocina';
update articulos_compra set categoria_id = (select id from categorias_articulo where nombre = 'Packaging') where categoria = 'Packaging';

alter table articulos_compra alter column categoria_id set not null;
alter table articulos_compra drop column categoria;

alter table ingredientes add column categoria_id bigint references categorias_articulo(id);
update ingredientes set categoria_id = (select id from categorias_articulo where nombre = 'Lácteos y Ovoproductos') where nombre = 'Huevina';
alter table ingredientes alter column categoria_id set not null;
