-- Ingrediente: agrupación N:M de variantes de artículo_compra intercambiables
-- entre sí (ej. "Huevina" agrupa "Huevina" normal y "Huevina Premium"), de
-- forma que receta_semielaborado/receta_producto_final puedan referenciar
-- el ingrediente en vez de un articulo_id concreto, dejando la elección de
-- variante para el momento de producción (según lo que haya en stock),
-- nunca resuelta automáticamente por el sistema.
--
-- Distinto de articulos_compra.categoria (taxonomía general de catálogo,
-- ej. "Verduras" agrupa Patata y Cebolla, que NO son intercambiables entre
-- sí) — se evita deliberadamente ese nombre/columna para no mezclar los
-- dos conceptos.
--
-- Relación N:M (no N:1): un mismo artículo puede pertenecer a varios
-- ingredientes a la vez (ej. una caja mediana como fallback de una caja
-- pequeña agotada) — de ahí la tabla puente articulo_ingrediente en vez de
-- una columna en articulos_compra. Mismo patrón de tabla puente ya usado
-- en este esquema (factura_compra_albaran): PK compuesta de las dos FKs,
-- sin id propio, on delete cascade.
--
-- Histórico existente: las 5 líneas reales de receta_semielaborado y
-- receta_producto_final NO se migran — siguen con articulo_id/
-- ingrediente_semielaborado_id directo. Solo se usará ingrediente_id en
-- líneas nuevas, cuando exista una segunda variante real que lo justifique
-- (hoy cada artículo de esas recetas tiene una única variante registrada,
-- así que no hay ninguna ambigüedad real que resolver todavía).
--
-- necesidades_pedidos() gana un tercer nivel de salida ('ingrediente'),
-- siempre hoja (nunca se recorre más allá, igual que 'articulo') — no
-- resuelve a qué artículo concreto atribuir la demanda, eso sigue siendo
-- decisión humana en la pantalla de producción. El resto de la función
-- (tablas temporales de pedidos, guarda de profundidad, niveles
-- 'producto_final' y 'semielaborado', nivel 'articulo' final) no cambia.
--
-- Probado en transacción de prueba (con ROLLBACK): caso real equivalente
-- (Huevina normal + Huevina Premium bajo el mismo ingrediente, receta de
-- prueba, necesidades_pedidos() devuelve el nivel 'ingrediente' correcto,
-- la simulación del desplegable devuelve lotes de ambos artículos y omite
-- sin error uno sin stock, 0 diffs en las 6 vistas de stock y en
-- necesidades_pedidos() sobre los pedidos reales). El CHECK de 3 vías se
-- probó exhaustivamente: las 3 combinaciones posibles de "2 campos
-- rellenos", "3 vacíos" y "3 rellenos" rechazadas en ambas tablas; los 3
-- casos válidos (uno por campo) aceptados en ambas tablas.

create table ingredientes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  unidad text not null,
  negocio_id uuid not null default 'a8acb3aa-e8f2-4a04-83f4-e6b0ca4e2d00' references negocios(id),
  created_at timestamptz not null default now()
);

alter table ingredientes enable row level security;
create policy "Acceso total temporal" on ingredientes for all
  using (auth.role() = 'authenticated' and negocio_id = 'a8acb3aa-e8f2-4a04-83f4-e6b0ca4e2d00'::uuid)
  with check (auth.role() = 'authenticated' and negocio_id = 'a8acb3aa-e8f2-4a04-83f4-e6b0ca4e2d00'::uuid);
grant select, insert, update, delete on ingredientes to authenticated;

create table articulo_ingrediente (
  articulo_id bigint not null references articulos_compra(id) on delete cascade,
  ingrediente_id bigint not null references ingredientes(id) on delete cascade,
  negocio_id uuid not null default 'a8acb3aa-e8f2-4a04-83f4-e6b0ca4e2d00' references negocios(id),
  primary key (articulo_id, ingrediente_id)
);

alter table articulo_ingrediente enable row level security;
create policy "Acceso total temporal" on articulo_ingrediente for all
  using (auth.role() = 'authenticated' and negocio_id = 'a8acb3aa-e8f2-4a04-83f4-e6b0ca4e2d00'::uuid)
  with check (auth.role() = 'authenticated' and negocio_id = 'a8acb3aa-e8f2-4a04-83f4-e6b0ca4e2d00'::uuid);
grant select, insert, update, delete on articulo_ingrediente to authenticated;

alter table receta_producto_final add column ingrediente_id bigint references ingredientes(id);
alter table receta_producto_final
  drop constraint solo_un_tipo_ingrediente_pf,
  add constraint solo_un_tipo_ingrediente_pf check (
    (articulo_id is not null and ingrediente_semielaborado_id is null and ingrediente_id is null) or
    (articulo_id is null and ingrediente_semielaborado_id is not null and ingrediente_id is null) or
    (articulo_id is null and ingrediente_semielaborado_id is null and ingrediente_id is not null)
  );

alter table receta_semielaborado add column ingrediente_id bigint references ingredientes(id);
alter table receta_semielaborado
  drop constraint solo_un_tipo_ingrediente,
  add constraint solo_un_tipo_ingrediente check (
    (articulo_id is not null and ingrediente_semielaborado_id is null and ingrediente_id is null) or
    (articulo_id is null and ingrediente_semielaborado_id is not null and ingrediente_id is null) or
    (articulo_id is null and ingrediente_semielaborado_id is null and ingrediente_id is not null)
  );

create or replace function necesidades_pedidos(p_pedido_ids bigint[])
returns table (
  nivel text,
  item_id bigint,
  nombre text,
  unidad text,
  cantidad_necesaria numeric
)
language plpgsql
as $$
declare
  v_max_profundidad constant int := 20;
  v_corte record;
begin
  drop table if exists tmp_necesidades_pedido_pf;
  create temporary table tmp_necesidades_pedido_pf on commit drop as
  select lpv.producto_final_id, sum(lpv.cantidad) as cantidad
  from lineas_pedido_venta lpv
  where lpv.pedido_id = any(p_pedido_ids) and lpv.producto_final_id is not null
  group by lpv.producto_final_id;

  drop table if exists tmp_necesidades_articulo_directo;
  create temporary table tmp_necesidades_articulo_directo on commit drop as
  select lpv.articulo_id, sum(lpv.cantidad) as cantidad
  from lineas_pedido_venta lpv
  where lpv.pedido_id = any(p_pedido_ids) and lpv.articulo_id is not null
  group by lpv.articulo_id;

  drop table if exists tmp_necesidades_explosion;
  create temporary table tmp_necesidades_explosion on commit drop as
  with recursive explosion as (
    select
      1 as profundidad,
      case
        when rpf.ingrediente_semielaborado_id is not null then 'semielaborado'
        when rpf.ingrediente_id is not null then 'ingrediente'
        else 'articulo'
      end as tipo,
      rpf.ingrediente_semielaborado_id as semielaborado_id,
      rpf.articulo_id as articulo_id,
      rpf.ingrediente_id as ingrediente_id,
      rpf.cantidad * ppf.cantidad as cantidad_necesaria
    from tmp_necesidades_pedido_pf ppf
    join receta_producto_final rpf on rpf.producto_final_id = ppf.producto_final_id

    union all

    select
      e.profundidad + 1,
      case
        when rs.ingrediente_semielaborado_id is not null then 'semielaborado'
        when rs.ingrediente_id is not null then 'ingrediente'
        else 'articulo'
      end,
      rs.ingrediente_semielaborado_id,
      rs.articulo_id,
      rs.ingrediente_id,
      rs.cantidad * e.cantidad_necesaria
    from explosion e
    join receta_semielaborado rs on rs.semielaborado_id = e.semielaborado_id
    where e.tipo = 'semielaborado' and e.profundidad < v_max_profundidad
  )
  select * from explosion;

  select s.id, s.nombre into v_corte
  from tmp_necesidades_explosion e
  join semielaborados s on s.id = e.semielaborado_id
  where e.tipo = 'semielaborado' and e.profundidad = v_max_profundidad
  limit 1;

  if found then
    raise exception 'necesidades_pedidos: recursión de receta cortada en profundidad % en el semielaborado "%" (id %) — probable ciclo en receta_semielaborado (un semielaborado que acaba consumiéndose a sí mismo, directa o indirectamente)',
      v_max_profundidad, v_corte.nombre, v_corte.id;
  end if;

  return query
  select 'producto_final'::text, ppf.producto_final_id, pf.nombre, null::text, ppf.cantidad
  from tmp_necesidades_pedido_pf ppf
  join productos_finales pf on pf.id = ppf.producto_final_id

  union all

  select 'semielaborado'::text, e.semielaborado_id, s.nombre, s.unidad, sum(e.cantidad_necesaria)
  from tmp_necesidades_explosion e
  join semielaborados s on s.id = e.semielaborado_id
  where e.tipo = 'semielaborado'
  group by e.semielaborado_id, s.nombre, s.unidad

  union all

  select 'ingrediente'::text, e.ingrediente_id, i.nombre, i.unidad, sum(e.cantidad_necesaria)
  from tmp_necesidades_explosion e
  join ingredientes i on i.id = e.ingrediente_id
  where e.tipo = 'ingrediente'
  group by e.ingrediente_id, i.nombre, i.unidad

  union all

  select 'articulo'::text, a.id, a.nombre, a.unidad,
    coalesce((select sum(ex.cantidad_necesaria) from tmp_necesidades_explosion ex where ex.tipo = 'articulo' and ex.articulo_id = a.id), 0)
    + coalesce((select ad.cantidad from tmp_necesidades_articulo_directo ad where ad.articulo_id = a.id), 0)
  from articulos_compra a
  where exists (select 1 from tmp_necesidades_explosion ex where ex.tipo = 'articulo' and ex.articulo_id = a.id)
     or exists (select 1 from tmp_necesidades_articulo_directo ad where ad.articulo_id = a.id);
end;
$$;
