-- Aviso (no bloqueo) de reparto cruzado: una producción de producto final
-- vinculada a un pedido (producciones_producto_final.pedido_id) cuyo stock
-- termina entregado en un albarán de un pedido distinto — o sin ningún
-- pedido vinculado, en cualquiera de las dos direcciones.
--
-- Contexto: detectado como bug real en AlbaranesVenta.jsx (lineaPedidoPara
-- atribuía mal las líneas cuando un pedido repetía producto, ya corregido
-- por separado) y, más en general, como una relación "blanda" sin ninguna
-- reconciliación hoy entre pedido<->producción y pedido<->albarán (ver
-- verificación previa). Se decidió tabla separada de
-- incidencias_stock_producto_final, no reutilizarla: el payload es
-- distinto (pedido esperado vs. pedido real, no una cantidad de déficit) y
-- no tiene hueco limpio en las columnas existentes sin añadir columnas
-- nullable que solo aplicarían a este motivo — mismo criterio que ya usa
-- este esquema al mantener incidencias_stock_articulo,
-- incidencias_stock_producto_final e incidencias_stock_semielaborado como
-- tablas separadas para el mismo tipo de concern a distinto nivel.
--
-- No bloquea nada (mismo patrón que evento_directo + incidencias_stock_*):
-- solo registra. La condición "pedido_esperado IS DISTINCT FROM
-- pedido_real" cubre en una sola comparación los dos casos con pedido
-- reservado/entregado a otro, el caso simétrico (reservado, entregado sin
-- pedido), y deja en silencio el caso "ambos null" — stock genérico
-- vendido sin pedido, que es la operación normal de hoy.

create table incidencias_reparto_pedido (
  id bigint generated by default as identity primary key,
  produccion_pf_id bigint not null references producciones_producto_final(id),
  linea_albaran_venta_id bigint not null references lineas_albaran_venta(id),
  pedido_esperado_id bigint references pedidos_venta(id),
  pedido_real_id bigint references pedidos_venta(id),
  detectada_en timestamptz not null default now(),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'regularizado', 'ignorado')),
  created_at timestamptz default now(),
  negocio_id uuid not null default 'a8acb3aa-e8f2-4a04-83f4-e6b0ca4e2d00' references negocios(id)
);

alter table incidencias_reparto_pedido enable row level security;

create policy "Acceso total temporal" on incidencias_reparto_pedido for all
  using (auth.role() = 'authenticated' and negocio_id = 'a8acb3aa-e8f2-4a04-83f4-e6b0ca4e2d00'::uuid)
  with check (auth.role() = 'authenticated' and negocio_id = 'a8acb3aa-e8f2-4a04-83f4-e6b0ca4e2d00'::uuid);

grant select, insert, update, delete on incidencias_reparto_pedido to authenticated;

create or replace function public.registrar_incidencia_reparto_pedido()
returns trigger
language plpgsql
as $$
declare
  v_pedido_esperado bigint;
  v_pedido_real bigint;
begin
  if NEW.produccion_pf_id is null then
    return NEW;
  end if;

  select pedido_id into v_pedido_esperado
  from producciones_producto_final
  where id = NEW.produccion_pf_id;

  if NEW.linea_pedido_id is not null then
    select pedido_id into v_pedido_real
    from lineas_pedido_venta
    where id = NEW.linea_pedido_id;
  else
    v_pedido_real := null;
  end if;

  if v_pedido_esperado is distinct from v_pedido_real then
    insert into incidencias_reparto_pedido (produccion_pf_id, linea_albaran_venta_id, pedido_esperado_id, pedido_real_id)
    values (NEW.produccion_pf_id, NEW.id, v_pedido_esperado, v_pedido_real);
  end if;

  return NEW;
end;
$$;

create trigger trg_registrar_incidencia_reparto_pedido
after insert or update on lineas_albaran_venta
for each row execute function registrar_incidencia_reparto_pedido();
