-- Venta contextual: el bloqueo por stock insuficiente en producto final
-- solo aplica a pedido_planificado. evento_directo (showcooking/evento)
-- nunca se bloquea, pero deja rastro en incidencias_stock_producto_final
-- para regularizar después. No toca UI. No toca la rama de mercadería.

-- ============================================================
-- 1. tipo_venta en albaranes_venta, con default protector.
-- ============================================================

alter table albaranes_venta add column tipo_venta text not null default 'pedido_planificado'
  check (tipo_venta in ('pedido_planificado', 'evento_directo'));

-- ============================================================
-- 2. Tabla de incidencias de stock negativo.
-- ============================================================

create table incidencias_stock_producto_final (
  id bigint generated by default as identity primary key,
  produccion_pf_id bigint not null references producciones_producto_final(id),
  linea_albaran_venta_id bigint not null references lineas_albaran_venta(id),
  cantidad_negativa numeric not null, -- magnitud del déficit (valor positivo)
  detectada_en timestamptz not null default now(),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'regularizado', 'ignorado')),
  created_at timestamptz default now()
);

alter table incidencias_stock_producto_final enable row level security;
create policy "Acceso total temporal" on incidencias_stock_producto_final for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
grant select, insert, update, delete on incidencias_stock_producto_final to authenticated;

-- ============================================================
-- 3. check_stock_producto_final: bloqueo condicional a tipo_venta.
--    Cambio mínimo, rama de mercadería/artículo intacta.
-- ============================================================

create or replace function public.check_stock_producto_final()
returns trigger
language plpgsql
as $function$
declare
  disponible numeric;
  v_tipo_venta text;
begin
  if NEW.produccion_pf_id is not null then
    select tipo_venta into v_tipo_venta from albaranes_venta where id = NEW.albaran_venta_id;

    select p.cantidad_producida - coalesce(sum(v.cantidad), 0)
        + coalesce((select sum(a.cantidad) from ajustes_producto_final a where a.produccion_pf_id = p.id), 0)
    into disponible
    from producciones_producto_final p
    left join lineas_albaran_venta v
      on v.produccion_pf_id = p.id
      and v.id is distinct from NEW.id
    where p.id = NEW.produccion_pf_id
    group by p.id, p.cantidad_producida;

    if disponible is null then
      raise exception 'La producción indicada no existe o no está cerrada';
    end if;

    if NEW.cantidad > disponible and v_tipo_venta is distinct from 'evento_directo' then
      raise exception 'Stock insuficiente: solo hay % unidades disponibles en ese lote de producción', disponible;
    end if;
  else
    select em.cantidad
      - coalesce((select sum(cantidad) from consumo_produccion where entrada_material_id = NEW.entrada_material_id), 0)
      - coalesce((select sum(cantidad) from consumo_produccion_pf where entrada_material_id = NEW.entrada_material_id), 0)
      - coalesce((select sum(v.cantidad) from lineas_albaran_venta v where v.entrada_material_id = NEW.entrada_material_id and v.id is distinct from NEW.id), 0)
      + coalesce((select sum(cantidad) from ajustes_articulo where entrada_material_id = NEW.entrada_material_id), 0)
    into disponible
    from entrada_material em
    where em.id = NEW.entrada_material_id;

    if disponible is null then
      raise exception 'El lote de artículo indicado no existe';
    end if;

    if NEW.cantidad > disponible then
      raise exception 'Stock insuficiente: solo hay % unidades disponibles en ese lote de artículo', disponible;
    end if;
  end if;

  return NEW;
end;
$function$;

-- ============================================================
-- 4. Registro de incidencia, en un trigger AFTER separado (la fila
--    de lineas_albaran_venta no existe todavía dentro del BEFORE de
--    check_stock_producto_final, así que la FK no sería válida ahí).
-- ============================================================

create or replace function public.registrar_incidencia_stock_negativo_pf()
returns trigger
language plpgsql
as $$
declare
  v_tipo_venta text;
  v_disponible numeric;
begin
  if NEW.produccion_pf_id is null then
    return NEW;
  end if;

  select tipo_venta into v_tipo_venta from albaranes_venta where id = NEW.albaran_venta_id;
  if v_tipo_venta is distinct from 'evento_directo' then
    return NEW;
  end if;

  select p.cantidad_producida - coalesce(sum(v.cantidad), 0)
      + coalesce((select sum(a.cantidad) from ajustes_producto_final a where a.produccion_pf_id = p.id), 0)
  into v_disponible
  from producciones_producto_final p
  left join lineas_albaran_venta v on v.produccion_pf_id = p.id
  where p.id = NEW.produccion_pf_id
  group by p.id, p.cantidad_producida;

  if v_disponible < 0 then
    insert into incidencias_stock_producto_final (produccion_pf_id, linea_albaran_venta_id, cantidad_negativa)
    values (NEW.produccion_pf_id, NEW.id, abs(v_disponible));
  end if;

  return NEW;
end;
$$;

create trigger trg_registrar_incidencia_stock_negativo_pf
after insert or update on lineas_albaran_venta
for each row execute function registrar_incidencia_stock_negativo_pf();
