-- Venta contextual, aplicada ahora al lado de producción: el bloqueo por
-- stock insuficiente al registrar consumo (semielaborado y producto final)
-- solo aplica a producción planificada. evento_directo (showcooking/evento)
-- nunca se bloquea, pero deja rastro para regularizar después. No toca UI.
--
-- check_consumo_produccion / check_consumo_produccion_pf ya eran triggers
-- AFTER diferidos (deferrable initially deferred) — a diferencia del caso
-- de ventas, aquí NO hay problema de FK-todavía-no-existe. Pero los nuevos
-- triggers de incidencias deben ser TAMBIÉN diferidos, para que calculen
-- el disponible final tras todos los cambios de una misma transacción
-- (p. ej. una edición vía RPC que toca varias líneas de golpe), no un
-- estado intermedio.

-- ============================================================
-- 1. tipo_produccion, con default protector, en ambas tablas de
--    producción (la que consume, no el lote de origen).
-- ============================================================

alter table producciones_semielaborado add column tipo_produccion text not null default 'planificada'
  check (tipo_produccion in ('planificada', 'evento_directo'));

alter table producciones_producto_final add column tipo_produccion text not null default 'planificada'
  check (tipo_produccion in ('planificada', 'evento_directo'));

-- ============================================================
-- 2. Dos tablas de incidencias — el origen consumido puede ser un
--    lote de artículo o un lote de semielaborado, entidades distintas
--    de producto_final, así que no se reutiliza incidencias_stock_producto_final.
--    Mismo patrón dual dos-FK-uno-obligatorio que consumo_produccion/_pf.
-- ============================================================

create table incidencias_stock_articulo (
  id bigint generated by default as identity primary key,
  entrada_material_id bigint not null references entrada_material(id),
  consumo_produccion_id bigint references consumo_produccion(id),
  consumo_produccion_pf_id bigint references consumo_produccion_pf(id),
  cantidad_negativa numeric not null,
  detectada_en timestamptz not null default now(),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'regularizado', 'ignorado')),
  created_at timestamptz default now(),
  constraint chk_incidencias_stock_articulo_origen check (
    (consumo_produccion_id is not null and consumo_produccion_pf_id is null)
    or (consumo_produccion_id is null and consumo_produccion_pf_id is not null)
  )
);

alter table incidencias_stock_articulo enable row level security;
create policy "Acceso total temporal" on incidencias_stock_articulo for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
grant select, insert, update, delete on incidencias_stock_articulo to authenticated;

create table incidencias_stock_semielaborado (
  id bigint generated by default as identity primary key,
  produccion_semielaborado_id bigint not null references producciones_semielaborado(id),
  consumo_produccion_id bigint references consumo_produccion(id),
  consumo_produccion_pf_id bigint references consumo_produccion_pf(id),
  cantidad_negativa numeric not null,
  detectada_en timestamptz not null default now(),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'regularizado', 'ignorado')),
  created_at timestamptz default now(),
  constraint chk_incidencias_stock_semielaborado_origen check (
    (consumo_produccion_id is not null and consumo_produccion_pf_id is null)
    or (consumo_produccion_id is null and consumo_produccion_pf_id is not null)
  )
);

alter table incidencias_stock_semielaborado enable row level security;
create policy "Acceso total temporal" on incidencias_stock_semielaborado for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
grant select, insert, update, delete on incidencias_stock_semielaborado to authenticated;

-- ============================================================
-- 3. check_consumo_produccion: bloqueo condicional a tipo_produccion
--    de la producción destino. Integridad y coherencia temporal
--    siguen incondicionales.
-- ============================================================

create or replace function public.check_consumo_produccion()
returns trigger
language plpgsql
as $$
declare
  v_fecha_destino date;
  v_fecha_origen date;
  v_disponible numeric;
  v_tipo_produccion text;
begin
  if (NEW.entrada_material_id is null) = (NEW.produccion_origen_id is null) then
    raise exception 'La línea de consumo debe referenciar exactamente un origen (artículo o producción)';
  end if;

  select fecha, tipo_produccion into v_fecha_destino, v_tipo_produccion
  from producciones_semielaborado
  where id = NEW.produccion_id;

  if v_fecha_destino is null then
    raise exception 'La producción destino (%) no existe', NEW.produccion_id;
  end if;

  if NEW.entrada_material_id is not null then
    select alc.fecha,
      em.cantidad
        - coalesce((select sum(cantidad) from consumo_produccion where entrada_material_id = NEW.entrada_material_id and id is distinct from NEW.id), 0)
        - coalesce((select sum(cantidad) from consumo_produccion_pf where entrada_material_id = NEW.entrada_material_id), 0)
        + coalesce((select sum(cantidad) from ajustes_articulo where entrada_material_id = NEW.entrada_material_id), 0)
    into v_fecha_origen, v_disponible
    from entrada_material em
    join albaranes_compra alc on alc.id = em.albaran_compra_id
    where em.id = NEW.entrada_material_id;

    if v_fecha_origen is null then
      raise exception 'El lote de artículo indicado (entrada_material %) no existe', NEW.entrada_material_id;
    end if;
  else
    if NEW.produccion_origen_id = NEW.produccion_id then
      raise exception 'Una producción no puede consumir de sí misma';
    end if;

    select p.fecha,
      p.cantidad_producida
        - coalesce((select sum(cantidad) from consumo_produccion where produccion_origen_id = NEW.produccion_origen_id and id is distinct from NEW.id), 0)
        - coalesce((select sum(cantidad) from consumo_produccion_pf where produccion_origen_id = NEW.produccion_origen_id), 0)
        + coalesce((select sum(cantidad) from ajustes_semielaborado where produccion_id = NEW.produccion_origen_id), 0)
    into v_fecha_origen, v_disponible
    from producciones_semielaborado p
    where p.id = NEW.produccion_origen_id and p.estado = 'cerrada';

    if v_fecha_origen is null then
      raise exception 'La producción de origen (%) no existe o no está cerrada', NEW.produccion_origen_id;
    end if;
  end if;

  if v_fecha_origen > v_fecha_destino then
    raise exception 'No se puede consumir un lote de fecha % en una producción con fecha % (el origen es posterior al destino)', v_fecha_origen, v_fecha_destino;
  end if;

  if NEW.cantidad > v_disponible and v_tipo_produccion is distinct from 'evento_directo' then
    raise exception 'Stock insuficiente en el lote de origen: solo hay % unidades disponibles', v_disponible;
  end if;

  return null;
end;
$$;

-- ============================================================
-- 4. check_consumo_produccion_pf: mismo cambio, destino es
--    producciones_producto_final.
-- ============================================================

create or replace function public.check_consumo_produccion_pf()
returns trigger
language plpgsql
as $$
declare
  v_fecha_destino date;
  v_fecha_origen date;
  v_disponible numeric;
  v_tipo_produccion text;
begin
  if (NEW.entrada_material_id is null) = (NEW.produccion_origen_id is null) then
    raise exception 'La línea de consumo debe referenciar exactamente un origen (artículo o producción)';
  end if;

  select fecha, tipo_produccion into v_fecha_destino, v_tipo_produccion
  from producciones_producto_final
  where id = NEW.produccion_pf_id;

  if v_fecha_destino is null then
    raise exception 'La producción destino (%) no existe', NEW.produccion_pf_id;
  end if;

  if NEW.entrada_material_id is not null then
    select alc.fecha,
      em.cantidad
        - coalesce((select sum(cantidad) from consumo_produccion where entrada_material_id = NEW.entrada_material_id), 0)
        - coalesce((select sum(cantidad) from consumo_produccion_pf where entrada_material_id = NEW.entrada_material_id and id is distinct from NEW.id), 0)
        + coalesce((select sum(cantidad) from ajustes_articulo where entrada_material_id = NEW.entrada_material_id), 0)
    into v_fecha_origen, v_disponible
    from entrada_material em
    join albaranes_compra alc on alc.id = em.albaran_compra_id
    where em.id = NEW.entrada_material_id;

    if v_fecha_origen is null then
      raise exception 'El lote de artículo indicado (entrada_material %) no existe', NEW.entrada_material_id;
    end if;
  else
    select p.fecha,
      p.cantidad_producida
        - coalesce((select sum(cantidad) from consumo_produccion where produccion_origen_id = NEW.produccion_origen_id), 0)
        - coalesce((select sum(cantidad) from consumo_produccion_pf where produccion_origen_id = NEW.produccion_origen_id and id is distinct from NEW.id), 0)
        + coalesce((select sum(cantidad) from ajustes_semielaborado where produccion_id = NEW.produccion_origen_id), 0)
    into v_fecha_origen, v_disponible
    from producciones_semielaborado p
    where p.id = NEW.produccion_origen_id and p.estado = 'cerrada';

    if v_fecha_origen is null then
      raise exception 'La producción de origen (%) no existe o no está cerrada', NEW.produccion_origen_id;
    end if;
  end if;

  if v_fecha_origen > v_fecha_destino then
    raise exception 'No se puede consumir un lote de fecha % en una producción con fecha % (el origen es posterior al destino)', v_fecha_origen, v_fecha_destino;
  end if;

  if NEW.cantidad > v_disponible and v_tipo_produccion is distinct from 'evento_directo' then
    raise exception 'Stock insuficiente en el lote de origen: solo hay % unidades disponibles', v_disponible;
  end if;

  return null;
end;
$$;

-- ============================================================
-- 5. Registro de incidencias — triggers AFTER diferidos (mismo
--    momento de evaluación que los de validación), uno por tabla
--    de consumo, cada uno decide en cuál de las dos tablas de
--    incidencias insertar según el tipo de origen de esa línea.
-- ============================================================

create or replace function public.registrar_incidencia_stock_negativo_consumo()
returns trigger
language plpgsql
as $$
declare
  v_tipo_produccion text;
  v_disponible numeric;
begin
  select tipo_produccion into v_tipo_produccion from producciones_semielaborado where id = NEW.produccion_id;
  if v_tipo_produccion is distinct from 'evento_directo' then
    return NEW;
  end if;

  if NEW.entrada_material_id is not null then
    select em.cantidad
      - coalesce((select sum(cantidad) from consumo_produccion where entrada_material_id = NEW.entrada_material_id), 0)
      - coalesce((select sum(cantidad) from consumo_produccion_pf where entrada_material_id = NEW.entrada_material_id), 0)
      + coalesce((select sum(cantidad) from ajustes_articulo where entrada_material_id = NEW.entrada_material_id), 0)
    into v_disponible
    from entrada_material em
    where em.id = NEW.entrada_material_id;

    if v_disponible < 0 then
      insert into incidencias_stock_articulo (entrada_material_id, consumo_produccion_id, cantidad_negativa)
      values (NEW.entrada_material_id, NEW.id, abs(v_disponible));
    end if;
  else
    select p.cantidad_producida
      - coalesce((select sum(cantidad) from consumo_produccion where produccion_origen_id = NEW.produccion_origen_id), 0)
      - coalesce((select sum(cantidad) from consumo_produccion_pf where produccion_origen_id = NEW.produccion_origen_id), 0)
      + coalesce((select sum(cantidad) from ajustes_semielaborado where produccion_id = NEW.produccion_origen_id), 0)
    into v_disponible
    from producciones_semielaborado p
    where p.id = NEW.produccion_origen_id;

    if v_disponible < 0 then
      insert into incidencias_stock_semielaborado (produccion_semielaborado_id, consumo_produccion_id, cantidad_negativa)
      values (NEW.produccion_origen_id, NEW.id, abs(v_disponible));
    end if;
  end if;

  return NEW;
end;
$$;

create constraint trigger trg_registrar_incidencia_stock_negativo_consumo
after insert or update on consumo_produccion
deferrable initially deferred
for each row execute function registrar_incidencia_stock_negativo_consumo();

create or replace function public.registrar_incidencia_stock_negativo_consumo_pf()
returns trigger
language plpgsql
as $$
declare
  v_tipo_produccion text;
  v_disponible numeric;
begin
  select tipo_produccion into v_tipo_produccion from producciones_producto_final where id = NEW.produccion_pf_id;
  if v_tipo_produccion is distinct from 'evento_directo' then
    return NEW;
  end if;

  if NEW.entrada_material_id is not null then
    select em.cantidad
      - coalesce((select sum(cantidad) from consumo_produccion where entrada_material_id = NEW.entrada_material_id), 0)
      - coalesce((select sum(cantidad) from consumo_produccion_pf where entrada_material_id = NEW.entrada_material_id), 0)
      + coalesce((select sum(cantidad) from ajustes_articulo where entrada_material_id = NEW.entrada_material_id), 0)
    into v_disponible
    from entrada_material em
    where em.id = NEW.entrada_material_id;

    if v_disponible < 0 then
      insert into incidencias_stock_articulo (entrada_material_id, consumo_produccion_pf_id, cantidad_negativa)
      values (NEW.entrada_material_id, NEW.id, abs(v_disponible));
    end if;
  else
    select p.cantidad_producida
      - coalesce((select sum(cantidad) from consumo_produccion where produccion_origen_id = NEW.produccion_origen_id), 0)
      - coalesce((select sum(cantidad) from consumo_produccion_pf where produccion_origen_id = NEW.produccion_origen_id), 0)
      + coalesce((select sum(cantidad) from ajustes_semielaborado where produccion_id = NEW.produccion_origen_id), 0)
    into v_disponible
    from producciones_semielaborado p
    where p.id = NEW.produccion_origen_id;

    if v_disponible < 0 then
      insert into incidencias_stock_semielaborado (produccion_semielaborado_id, consumo_produccion_pf_id, cantidad_negativa)
      values (NEW.produccion_origen_id, NEW.id, abs(v_disponible));
    end if;
  end if;

  return NEW;
end;
$$;

create constraint trigger trg_registrar_incidencia_stock_negativo_consumo_pf
after insert or update on consumo_produccion_pf
deferrable initially deferred
for each row execute function registrar_incidencia_stock_negativo_consumo_pf();
