-- Producto final: producción y venta no son 1:1 (merma), y el producto
-- final caduca. No toca UI. No toca la rama de mercadería/artículo de
-- check_stock_producto_final.

-- ============================================================
-- 1. Caducidad: días por defecto a nivel de tipo de producto,
--    fecha real calculada al cerrar la producción y editable después.
-- ============================================================

alter table productos_finales add column dias_caducidad_default integer;
alter table producciones_producto_final add column fecha_caducidad date;

create or replace function public.calcular_fecha_caducidad_pf()
returns trigger
language plpgsql
as $$
declare
  v_dias integer;
begin
  if OLD.estado = 'abierta' and NEW.estado = 'cerrada' and NEW.fecha_caducidad is null then
    select dias_caducidad_default into v_dias from productos_finales where id = NEW.producto_final_id;
    if v_dias is not null then
      NEW.fecha_caducidad := NEW.fecha + v_dias;
    end if;
  end if;
  return NEW;
end;
$$;

create trigger trg_calcular_fecha_caducidad_pf
before update on producciones_producto_final
for each row execute function calcular_fecha_caducidad_pf();

-- ============================================================
-- 2. Merma: mismo patrón que ajustes_articulo / ajustes_semielaborado,
--    con motivo de categoría controlada (decisión explícita, distinta
--    a las otras dos tablas de ajustes, que se quedan en texto libre).
-- ============================================================

create table ajustes_producto_final (
  id bigint generated by default as identity primary key,
  produccion_pf_id bigint not null references producciones_producto_final(id),
  cantidad numeric not null, -- con signo: negativo = merma, positivo = corrección a favor
  motivo_categoria text not null check (motivo_categoria in ('caducado', 'roto', 'evento_no_consumido', 'otro')),
  motivo_detalle text,
  fecha date not null default current_date,
  created_at timestamptz default now()
);

alter table ajustes_producto_final enable row level security;
create policy "Acceso total temporal" on ajustes_producto_final for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
grant select, insert, update, delete on ajustes_producto_final to authenticated;

-- ============================================================
-- 3. Fórmula de stock ampliada: producido - vendido + ajustes
--    (ajustes.cantidad ya lleva el signo). Dos sitios: la vista de
--    lectura, y el trigger de validación de venta (que NO lee la
--    vista, tiene su propio cálculo duplicado — mismo patrón que el
--    resto de triggers de este sistema).
-- ============================================================

create or replace view stock_lotes_producto_final as
select p.id as produccion_id,
  p.producto_final_id,
  pf.nombre,
  p.cantidad_producida
    - coalesce((select sum(v.cantidad) from lineas_albaran_venta v where v.produccion_pf_id = p.id), 0)
    + coalesce((select sum(a.cantidad) from ajustes_producto_final a where a.produccion_pf_id = p.id), 0)
    as stock_disponible,
  p.fecha,
  p.fecha_caducidad
from producciones_producto_final p
join productos_finales pf on pf.id = p.producto_final_id
where p.estado = 'cerrada';

create or replace function public.check_stock_producto_final()
returns trigger
language plpgsql
as $function$
declare
  disponible numeric;
begin
  if NEW.produccion_pf_id is not null then
    select p.cantidad_producida - coalesce(sum(v.cantidad), 0)
        + coalesce((select sum(a.cantidad) from ajustes_producto_final a where a.produccion_pf_id = p.id), 0)
    into disponible
    from producciones_producto_final p
    left join lineas_albaran_venta v
      on v.produccion_pf_id = p.id
      and v.id is distinct from NEW.id
    where p.id = NEW.produccion_pf_id
    group by p.id, p.cantidad_producida;

    if disponible is null then
      raise exception 'La producción indicada no existe o no está cerrada';
    end if;

    if NEW.cantidad > disponible then
      raise exception 'Stock insuficiente: solo hay % unidades disponibles en ese lote de producción', disponible;
    end if;
  else
    select em.cantidad
      - coalesce((select sum(cantidad) from consumo_produccion where entrada_material_id = NEW.entrada_material_id), 0)
      - coalesce((select sum(cantidad) from consumo_produccion_pf where entrada_material_id = NEW.entrada_material_id), 0)
      - coalesce((select sum(v.cantidad) from lineas_albaran_venta v where v.entrada_material_id = NEW.entrada_material_id and v.id is distinct from NEW.id), 0)
      + coalesce((select sum(cantidad) from ajustes_articulo where entrada_material_id = NEW.entrada_material_id), 0)
    into disponible
    from entrada_material em
    where em.id = NEW.entrada_material_id;

    if disponible is null then
      raise exception 'El lote de artículo indicado no existe';
    end if;

    if NEW.cantidad > disponible then
      raise exception 'Stock insuficiente: solo hay % unidades disponibles en ese lote de artículo', disponible;
    end if;
  end if;

  return NEW;
end;
$function$;
