-- Flujo A/B de compras: pedido de compra opcional (planificada) vs. compra
-- directa/spot (sin pedido previo). No toca producción ni semielaborados.

-- ============================================================
-- 1. Cabecera de pedido de compra
-- ============================================================

create table pedidos_compra (
  id bigint generated by default as identity primary key,
  proveedor_id bigint not null references proveedores(id),
  fecha date not null default current_date,
  fecha_entrega_prevista date,
  estado text not null default 'pendiente', -- pendiente | recibido | cancelado
  notas text,
  codigo_pedido text,
  created_at timestamptz default now()
);

alter table pedidos_compra enable row level security;
create policy "Acceso total temporal" on pedidos_compra for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
grant select, insert, update, delete on pedidos_compra to authenticated;

create or replace function public.trg_codigo_oc()
returns trigger
language plpgsql
as $$
begin
  NEW.codigo_pedido := generar_codigo('OC');
  return NEW;
end;
$$;

create trigger trg_generar_codigo_oc
before insert on pedidos_compra
for each row execute function trg_codigo_oc();

-- ============================================================
-- 2. Líneas de pedido de compra: siempre un artículo (a diferencia
--    de lineas_pedido_venta, aquí no hay doble origen posible).
-- ============================================================

create table lineas_pedido_compra (
  id bigint generated by default as identity primary key,
  pedido_compra_id bigint not null references pedidos_compra(id) on delete cascade,
  articulo_id bigint not null references articulos_compra(id),
  cantidad numeric not null,
  precio_unitario numeric,
  created_at timestamptz default now()
);

alter table lineas_pedido_compra enable row level security;
create policy "Acceso total temporal" on lineas_pedido_compra for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
grant select, insert, update, delete on lineas_pedido_compra to authenticated;

-- ============================================================
-- 3. albaranes_compra: pedido_compra_id nullable + tipo_origen,
--    con backfill del histórico existente (sin inventar pedidos).
-- ============================================================

alter table albaranes_compra
  add column pedido_compra_id bigint references pedidos_compra(id),
  add column tipo_origen text;

update albaranes_compra set tipo_origen = 'compra_directa' where pedido_compra_id is null;

alter table albaranes_compra
  alter column tipo_origen set not null,
  add constraint chk_albaranes_compra_origen check (
    (tipo_origen = 'pedido' and pedido_compra_id is not null)
    or
    (tipo_origen = 'compra_directa' and pedido_compra_id is null)
  );

-- ============================================================
-- 4. Trazabilidad línea a línea: qué línea de entrada_material
--    cubre qué línea de pedido de compra.
-- ============================================================

alter table entrada_material add column linea_pedido_compra_id bigint references lineas_pedido_compra(id);

-- ============================================================
-- 5. Estado automático del pedido de compra: pendiente -> recibido
--    cuando todas sus líneas están cubiertas por cantidad recibida.
-- ============================================================

create or replace function public.actualizar_estado_pedido_compra()
returns trigger
language plpgsql
as $$
declare
  v_pedido_id bigint;
  v_pendiente boolean;
begin
  select pedido_compra_id into v_pedido_id
  from lineas_pedido_compra
  where id = coalesce(NEW.linea_pedido_compra_id, OLD.linea_pedido_compra_id);

  if v_pedido_id is null then
    return coalesce(NEW, OLD);
  end if;

  select exists (
    select 1
    from lineas_pedido_compra lp
    where lp.pedido_compra_id = v_pedido_id
      and lp.cantidad > coalesce((select sum(cantidad) from entrada_material where linea_pedido_compra_id = lp.id), 0)
  ) into v_pendiente;

  update pedidos_compra
  set estado = case when v_pendiente then estado else 'recibido' end
  where id = v_pedido_id and estado <> 'cancelado';

  return coalesce(NEW, OLD);
end;
$$;

create trigger trg_actualizar_estado_pedido_compra
after insert or update or delete on entrada_material
for each row execute function actualizar_estado_pedido_compra();
