-- Módulo de Pedidos de venta: cliente pide (producto final o mercadería) ->
-- se enlaza con la producción que lo cubre -> se enlaza con el albarán de
-- venta que lo entrega. Enlace blando (trazabilidad), no reserva dura: el
-- stock sigue siendo de libre disposición como hasta ahora.

-- ============================================================
-- 1. Cabecera de pedido
-- ============================================================

create table pedidos_venta (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references clientes(id),
  fecha date not null default current_date,
  fecha_entrega_prevista date,
  estado text not null default 'pendiente', -- pendiente | en_produccion | servido | cancelado
  notas text,
  codigo_pedido text,
  created_at timestamptz default now()
);

alter table pedidos_venta enable row level security;
create policy "Acceso total temporal" on pedidos_venta for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
-- RLS controla filas, no sustituye al GRANT de tabla que exige Postgres.
grant select, insert, update, delete on pedidos_venta to authenticated;

create or replace function public.trg_codigo_ov()
returns trigger
language plpgsql
as $$
begin
  NEW.codigo_pedido := generar_codigo('OV');
  return NEW;
end;
$$;

create trigger trg_generar_codigo_ov
before insert on pedidos_venta
for each row execute function trg_codigo_ov();

-- ============================================================
-- 2. Líneas de pedido: producto final (necesita producción) o
--    mercadería (artículo de compra ya listo para vender).
-- ============================================================

create table lineas_pedido_venta (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references pedidos_venta(id) on delete cascade,
  producto_final_id bigint references productos_finales(id),
  articulo_id bigint references articulos_compra(id),
  cantidad numeric not null,
  precio_unitario numeric,
  created_at timestamptz default now(),
  constraint chk_lineas_pedido_un_origen check ((producto_final_id is not null) <> (articulo_id is not null))
);

alter table lineas_pedido_venta enable row level security;
create policy "Acceso total temporal" on lineas_pedido_venta for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
grant select, insert, update, delete on lineas_pedido_venta to authenticated;

-- ============================================================
-- 3. Enlaces de trazabilidad en tablas existentes.
-- ============================================================

alter table producciones_producto_final add column pedido_id bigint references pedidos_venta(id);

alter table lineas_albaran_venta
  alter column producto_final_id drop not null,
  alter column produccion_pf_id drop not null,
  add column articulo_id bigint references articulos_compra(id),
  add column entrada_material_id bigint references entrada_material(id),
  add column linea_pedido_id bigint references lineas_pedido_venta(id);

alter table lineas_albaran_venta add constraint chk_lineas_albaran_venta_origen check (
  (producto_final_id is not null and produccion_pf_id is not null and articulo_id is null and entrada_material_id is null)
  or
  (articulo_id is not null and entrada_material_id is not null and producto_final_id is null and produccion_pf_id is null)
);

-- ============================================================
-- 4. Trigger de stock de venta, ampliado con la rama de mercadería.
--    La rama de producto final se deja intacta (mismo cálculo que
--    ya existía) para no arriesgar el flujo de venta actual.
-- ============================================================

create or replace function public.check_stock_producto_final()
returns trigger
language plpgsql
as $function$
declare
  disponible numeric;
begin
  if NEW.produccion_pf_id is not null then
    select p.cantidad_producida - coalesce(sum(v.cantidad), 0)
    into disponible
    from producciones_producto_final p
    left join lineas_albaran_venta v
      on v.produccion_pf_id = p.id
      and v.id is distinct from NEW.id
    where p.id = NEW.produccion_pf_id
    group by p.cantidad_producida;

    if disponible is null then
      raise exception 'La producción indicada no existe o no está cerrada';
    end if;

    if NEW.cantidad > disponible then
      raise exception 'Stock insuficiente: solo hay % unidades disponibles en ese lote de producción', disponible;
    end if;
  else
    select em.cantidad
      - coalesce((select sum(cantidad) from consumo_produccion where entrada_material_id = NEW.entrada_material_id), 0)
      - coalesce((select sum(cantidad) from consumo_produccion_pf where entrada_material_id = NEW.entrada_material_id), 0)
      - coalesce((select sum(v.cantidad) from lineas_albaran_venta v where v.entrada_material_id = NEW.entrada_material_id and v.id is distinct from NEW.id), 0)
      + coalesce((select sum(cantidad) from ajustes_articulo where entrada_material_id = NEW.entrada_material_id), 0)
    into disponible
    from entrada_material em
    where em.id = NEW.entrada_material_id;

    if disponible is null then
      raise exception 'El lote de artículo indicado no existe';
    end if;

    if NEW.cantidad > disponible then
      raise exception 'Stock insuficiente: solo hay % unidades disponibles en ese lote de artículo', disponible;
    end if;
  end if;

  return NEW;
end;
$function$;

-- ============================================================
-- 5. Actualización automática de pedidos_venta.estado.
-- ============================================================

create or replace function public.actualizar_estado_pedido_por_produccion()
returns trigger
language plpgsql
as $$
begin
  if NEW.pedido_id is not null then
    update pedidos_venta
    set estado = 'en_produccion'
    where id = NEW.pedido_id and estado = 'pendiente';
  end if;
  return NEW;
end;
$$;

create trigger trg_actualizar_estado_pedido_por_produccion
after insert or update on producciones_producto_final
for each row execute function actualizar_estado_pedido_por_produccion();

create or replace function public.actualizar_estado_pedido_por_servicio()
returns trigger
language plpgsql
as $$
declare
  v_pedido_id bigint;
  v_pendiente boolean;
begin
  select pedido_id into v_pedido_id
  from lineas_pedido_venta
  where id = coalesce(NEW.linea_pedido_id, OLD.linea_pedido_id);

  if v_pedido_id is null then
    return coalesce(NEW, OLD);
  end if;

  select exists (
    select 1
    from lineas_pedido_venta lp
    where lp.pedido_id = v_pedido_id
      and lp.cantidad > coalesce((select sum(cantidad) from lineas_albaran_venta where linea_pedido_id = lp.id), 0)
  ) into v_pendiente;

  update pedidos_venta
  set estado = case when v_pendiente then estado else 'servido' end
  where id = v_pedido_id and estado <> 'cancelado';

  return coalesce(NEW, OLD);
end;
$$;

create trigger trg_actualizar_estado_pedido_por_servicio
after insert or update or delete on lineas_albaran_venta
for each row execute function actualizar_estado_pedido_por_servicio();
